//
// Created by zhaoliang on 17/07/26.
//

#ifndef NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H
#define NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H

#define SCENARIOTIME 10000
#define CONTENT_NUMBER 26
#define CONTENT_NUMBER_STR "26"
#define CACHE_SIZE 10000


#endif //NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H
