//
// Created by zhaoliang on 17/07/26.
//

#ifndef NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H
#define NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H

#define SCENARIOTIME 20000
#define CONTENT_NUMBER_STR "26"
#define CACHE_SIZE 1000
#define DASH_CLIENT_TYPE "ns3::ndn::DashClientZipf"



#endif //NDNSIM_DASH_TEST_SCENARIO_PARAMETERS_H_H
