#ifndef DASN_PARAMETER_H
#define DASN_PARAMETER_H

#define FREQGAIN 1.5
#define NDN_PAYLOAD_SIZE 8000
#define DATA_PACKET_SIZE 8034
#define IPSCYCLE 15
#define SEGMENT_LENGTH 2
#define PAYLOADSIZE 8000
#define IPSTHRESHOLD 0.01
#define WINDOW 3

#endif
